### ISSUE TITLE
Kill as non-admin

### ISSUE THREAD

**Issue by Rakambda** [8LWXpg/ptr#11]
### Description

Hello, thanks for this little tool.

I started using it at work however the auto-restart of powershell is a bit cumbersome as it requires admin elevation, which is not always the best in a company environment (and denying the elevation prompt stops the command as we get `error: Failed to kill PowerToys: Operation was cancelled by the user. (0x800704C7)`).

In my case PowerToys is installed through Scoop as a portable app and doesn't require admin rights. So as it's started as a user, I guess, it doesn't require admin rights to be killed. Executing the command in my terminal with my own user works (seeing several lines `operation successfull : process with PID xxx was killed`).

Would it be possible to either (though some kind of config of command flag) : 
* Use a user-level process to execute the taskkill insted of forcing it to be admin (that'd be preferable i think)
* Disable the auto-kill
* Before killing check if powertoys is started (even if I kill powertoys manually, it still tries to kill it and ends up in an error)

**Comment by 8LWXpg** [comment]
Added the new field in `0.9.0`, change `admin` field `version.toml` to `false` should fix this issue.
