### ISSUE TITLE
x64 explicit failure

### ISSUE THREAD

**Issue by zQueal** [8LWXpg/ptr#6]
Trying to add a plugin;

```cli
❯ ptr a Winget bostrot/PowerToysRunPluginWinget
error: No asset found that contains 'x64'
```

The release page of the plugin contains only `winget-powertoys-1.3.0.zip` I understand the precaution, but why __must__ a release conform to these standards? Seems dubious--especially explicitly requiring it without any way to force it.

**Comment by 8LWXpg** [comment]
The issue lies in the uncertainty of matching release assets. This is simply the result of trying to match assets.

However, I can add a manual fallback if matching fails.
